apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: token-resource
spec:
  selector:
    matchLabels:
      app: token-resource
  template:
    metadata:
      labels:
        app: token-resource
    spec:
      containers:
      - name: token-resource
        image: docker.io/uablrek/token-resource:latest
        imagePullPolicy: IfNotPresent
        command:
          - "/token-resource"
          - "-loglevel"
          - "0"
          - "-socket"
          - "token-resource"
          - "-count"
          - "2"
          - "-resource"
          - "example.com/token"
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/lib/kubelet/device-plugins
          name: device-plugins
      volumes:
      - hostPath:
          path: /var/lib/kubelet/device-plugins
        name: device-plugins
